name: 'climate_analysis_env'
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - ipywidgets
  - ipython>=7.15
  - altair_saver
  - altair>=4.1.0
  - pip
  - matplotlib>=3.2.2
  - pandas>=1.3.*